### ISSUE TITLE
opam install conduit fails

### ISSUE THREAD

**Issue by neolem** [mirage/ocaml-conduit#192]
```The following actions will be performed:
  - install conduit 0.14.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[conduit] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of conduit failed at "make".
Processing  1/1: [conduit: ocamlfind remove]
#=== ERROR while installing conduit.0.14.1 ====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1
# compiler     4.03.0+flambda
# exit-code    2
# env-file     /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/conduit-85372-d2c37b.env
# stdout-file  /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/conduit-85372-d2c37b.out
# stderr-file  /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/conduit-85372-d2c37b.err
### stdout ###
# [...]
# ocamlfind ocamlc -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/resolver.cmo lib/resolver.ml
# ocamlfind ocamlopt -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/conduit.cmx lib/conduit.ml
# ocamlfind ocamlopt -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/conduit_trie.cmx lib/conduit_trie.ml
# ocamlfind ocamlopt -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/resolver.cmx lib/resolver.ml
# ocamlfind ocamldep -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -modules lib/resolver_lwt.mli > lib/resolver_lwt.mli.depends
# ocamlfind ocamlc -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/resolver_lwt.cmi lib/resolver_lwt.mli
# + ocamlfind ocamlc -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.03.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/resolver_lwt.cmi lib/resolver_lwt.mli
# File "/tmp/ocamlpp211799", line 3, characters 42-50:
# Error: Unbound module Lwt
# Command exited with code 2.
### stderr ###
# + ocaml discover.ml
# File "./discover.ml", line 53, characters 26-42:
# Warning 3: deprecated: String.uppercase
# Use String.uppercase_ascii instead.
# File "./discover.ml", line 101, characters 11-27:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/bgurung/.opam/4.03.0+flambda/lib/ocaml, /home/bgurung/.opam/4.03.0+flambda/lib/ocaml/compiler-libs
# make: *** [all] Error 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install conduit 0.14.1
No changes have been performed
```
Both `lwt` and `async` packages are installed.

**Comment by bpdp** [comment]
assumming that lwt and ssl are installed, you may modify Makefile from this line:

> OCAMLBUILD = ocamlbuild -use-ocamlfind -classic-display \
> 	-cflags "-w A-4-33-40-41-42-43-34-44" 

to

> OCAMLBUILD = ocamlbuild -use-ocamlfind -classic-display \
> 	-cflags "-w A-4-33-40-41-42-43-34-44" -package lwt -package ssl

**Comment by neolem** [comment]
@bpdp Hmmm .. I am trying to install from opam. Do you mean to download source and build locally?

**Comment by neolem** [comment]
I tried on ocaml 4.04+flambda branch and still unable to install `conduit` from opam. However the error I am getting is something to do with `core`.
```
ocamlfind ocamlc -c -w A-4-33-40-41-42-43-34-44 -g -bin-annot -short-paths -principal -thread -strict-sequence -pp /home/bgurung/.opam/4.04.0+flambda/build/conduit.0.14.1/ppx -package sexplib -package ipaddr -package cstruct -package uri -package stringext -package logs -I lib -I tests/async -I tests/mirage -I tests/unix -o lib/conduit_async.cmi lib/conduit_async.mli
# File "/tmp/ocamlpp11219a", line 3, characters 5-13:
# Error: Unbound module Core
# Command exited with code 2.
``` 
`Core` is installed.

**Comment by edwintorok** [comment]
Looks like same problem as in #189 , can you try installing conduit from git? (if you use opam then do `opam pin add --dev conduit`)

**Comment by neolem** [comment]
@edwintorok Yep, pinned dev version works on 4.04.

**Comment by tempodox** [comment]
I had 

> Error: Unbound module Lwt

when installing thru opam although lwt is installed. The `pin` above solved that, too.

**Comment by rgrinberg** [comment]
There should be no need to pin anymore. 0.14.2 solved this problem. Apologies for this issue.
